name: custom_map_markers
description: A package that turns runtime widgets into map marker icons.
version: 0.0.1
homepage: https://github.com/IbrahimTabba/custom_map_markers

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.0.11
  synchronized: ^3.0.0
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
